from sqlalchemy import Column, Integer, String, DateTime, Text
from sqlalchemy.sql import func
from app.database.db import Base


class DetectionAlert(Base):
    """
    Persistent detection alert generated by the rule engine.
    """

    __tablename__ = "detection_alerts"

    id = Column(Integer, primary_key=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    rule_id = Column(String, nullable=False)
    rule_name = Column(String, nullable=False)
    severity = Column(String, nullable=False)
    confidence_score = Column(Integer, default=0)
    category = Column(String, default="general")
    status = Column(String, default="open")
    summary = Column(Text)
    evidence_json = Column(Text)
    mitre_json = Column(Text)
    ioc_json = Column(Text)
    actions_json = Column(Text)
    fingerprint = Column(String, unique=True, index=True, nullable=False)
